services:
  booking-service:
    image: bookingservice
    build:
      context: .
      dockerfile: BookingService/Dockerfile
  
  flight-service:
    image: flightservice
    build:
      context: .
      dockerfile: FlightService/Dockerfile
  
  booking-db:
    image: postgres:16
    environment:
      - POSTGRES_DB=bookingdb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - booking-db-data:/var/lib/postgresql/data
  
  flight-db:
    image: postgres:16
    environment:
      - POSTGRES_DB=flightdb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5433:5432"
    volumes:
      - flight-db-data:/var/lib/postgresql/data
  
volumes:
  booking-db-data:
  flight-db-data:
