services:
  booking-service:
    image: bookingservice
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    build:
      context: .
      dockerfile: BookingService/Dockerfile
  
  flight-service:
    image: flightservice
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    build:
      context: .
      dockerfile: FlightService/Dockerfile
      
  payment-service:
    image: paymentservice
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    build:
      context: .
      dockerfile: PaymentService/Dockerfile
  
  booking-service-db:
    image: mcr.microsoft.com/azure-sql-edge:latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=StrongPass123!
      - MSSQL_PID=Developer
      - MSSQL_AGENT_ENABLED=true
    ports:
      - "1433:1433"
    volumes:
      - booking-service-db-data-local:/var/opt/mssql
  
  flight-service-db:
    image: mcr.microsoft.com/azure-sql-edge:latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=StrongPass123!
      - MSSQL_PID=Developer
      - MSSQL_AGENT_ENABLED=true
    ports:
      - "1434:1433"
    volumes:
      - flight-service-db-data-local:/var/opt/mssql
        
  payment-service-db:
    image: mcr.microsoft.com/azure-sql-edge:latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=StrongPass123!
      - MSSQL_PID=Developer
      - MSSQL_AGENT_ENABLED=true
    ports:
      - "1435:1433"
    volumes:
      - payment-service-db-data-local:/var/opt/mssql
    
  redis:
    image: redis/redis-stack:latest
    ports:
      - "6379:6379"
      - "8001:8001" # Redis Insight
    volumes:
      - redis-data:/data

volumes:
  booking-service-db-data-local:
  flight-service-db-data-local:
  payment-service-db-data-local:
  redis-data:
