name: Build and Push Docker Images CI

on:
  push:
    branches: [ main ]
    paths:
      - 'FlightService/**'
      - 'BookingService/**'
  # Manual trigger option
  workflow_dispatch:

jobs:
  flight-service:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-buildx-action@v2
      - uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push Flight Service
        uses: docker/build-push-action@v4
        with:
          context: .  # Use repository root as context
          file: ./FlightService/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/flightservice:latest
  
  booking-service:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-buildx-action@v2
      - uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push Booking Service
        uses: docker/build-push-action@v4
        with:
          context: .  # Use repository root as context
          file: ./BookingService/Dockerfile 
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/bookingservice:latest
