name: Trigger auto deployment for booking-service

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/booking-service-AutoDeployTrigger-7b9bc741-3a81-44b4-bec4-0b9c88ac5c84.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.BOOKINGSERVICE_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.BOOKINGSERVICE_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.BOOKINGSERVICE_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          registryUrl: docker.io
          registryUsername: ${{ secrets.BOOKINGSERVICE_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.BOOKINGSERVICE_REGISTRY_PASSWORD }}
          containerAppName: booking-service
          resourceGroup: dev
          imageToBuild: carlbeullens86/booking-service:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


